# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lean Prover / mathlib
email: rls890@vu.nl
description: > # this means to ignore newlines until "baseurl:"
  The homepage for the mathlib library for the Lean theorem prover.
  Contains an archive of the Zulip chat for discussions about Lean and mathlib.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leanprover-community.github.io" # the base hostname & protocol for your site

source: "source"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  smart_quotes: ["apos", "apos", "quot", "quot"]

exclude: ["*.py"]

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
# disqus_shortname:

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
